[parity]
chain = "demo-spec.json"
base_path = "/tmp/parity"
[network]
port = 30300
[rpc]
port = 8540
interface = "0.0.0.0"
#hosts = ["0.0.0.0/0"]
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8180
#interface = "0.0.0.0"
[dapps]
port = 8080
[mining]
engine_signer = "0x00Aa39d30F0D20FF03a22cCfc30B7EfbFca597C2"
reseal_on_txs = "none"
